#!/usr/bin/env python3
"""Check SEC EDGAR for new filings from a watch list of companies.

Uses the free EDGAR "submissions" JSON API (no API key required):

    https://data.sec.gov/submissions/CIK##########.json

The last accession number seen per company is stored in a small JSON state
file, so each re-run only reports filings that appeared since last time.

Usage:
    python3 edgar_watcher.py                 # normal run
    python3 edgar_watcher.py --all           # ignore state, show recent filings
    python3 edgar_watcher.py --dry-run       # report, but don't update state
    python3 edgar_watcher.py --forms 8-K,10-Q

Only the Python standard library is used, so there is nothing to install.
"""

from __future__ import annotations

import argparse
import json
import os
import smtplib
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

import emailer

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# The SEC requires every automated request to identify who is making it.
# See https://www.sec.gov/os/webmaster-faq#developers
# Edit the line below (or set the SEC_USER_AGENT environment variable) to
# include your own name and email address.
DEFAULT_USER_AGENT = "CRO-Filings-Watcher/1.0 (your.name@example.com)"

SUBMISSIONS_URL = "https://data.sec.gov/submissions/CIK{cik}.json"
ARCHIVES_URL = "https://www.sec.gov/Archives/edgar/data/{cik_int}/{accession_nodash}"

HERE = Path(__file__).resolve().parent
DEFAULT_COMPANIES_FILE = HERE / "companies.json"
DEFAULT_STATE_FILE = HERE / "state.json"

# The SEC asks for no more than 10 requests per second. One request every
# fifth of a second is well inside that and is polite for a small script.
REQUEST_DELAY_SECONDS = 0.2
REQUEST_TIMEOUT_SECONDS = 30


# ---------------------------------------------------------------------------
# Loading the watch list and the saved state
# ---------------------------------------------------------------------------

def load_companies(path: Path) -> list[dict]:
    """Read companies.json and return the list of companies to check."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise SystemExit(f"Company list not found: {path}")
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Company list {path} is not valid JSON: {exc}")

    companies = data.get("companies") if isinstance(data, dict) else data
    if not isinstance(companies, list) or not companies:
        raise SystemExit(f"No companies found in {path}")

    cleaned = []
    for entry in companies:
        cik = str(entry.get("cik", "")).strip()
        name = str(entry.get("name", "")).strip()
        if not cik.isdigit() or not name:
            raise SystemExit(f"Bad entry in {path} (needs numeric 'cik' and 'name'): {entry!r}")
        # EDGAR wants the CIK zero-padded to 10 digits in the URL.
        cleaned.append({"name": name, "ticker": entry.get("ticker", ""), "cik": cik.zfill(10)})
    return cleaned


def load_state(path: Path) -> dict:
    """Read the state file. A missing or unreadable file means 'first run'."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {}
    except (json.JSONDecodeError, OSError) as exc:
        print(f"Warning: could not read state file {path} ({exc}); treating as first run.",
              file=sys.stderr)
        return {}
    return data.get("companies", {}) if isinstance(data, dict) else {}


def save_state(path: Path, state: dict) -> None:
    """Write the state file atomically, so an interrupted run can't corrupt it."""
    payload = {
        "_comment": "Auto-generated by edgar_watcher.py. Delete this file to start over.",
        "companies": state,
    }
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    tmp.replace(path)


# ---------------------------------------------------------------------------
# Talking to EDGAR
# ---------------------------------------------------------------------------

def fetch_submissions(cik: str, user_agent: str) -> dict:
    """Download and parse the submissions JSON for one company."""
    request = urllib.request.Request(
        SUBMISSIONS_URL.format(cik=cik),
        headers={
            "User-Agent": user_agent,
            "Accept": "application/json",
            # Ask for an uncompressed response; urllib will not un-gzip for us.
            "Accept-Encoding": "identity",
        },
    )
    with urllib.request.urlopen(request, timeout=REQUEST_TIMEOUT_SECONDS) as response:
        return json.loads(response.read().decode("utf-8"))


def filing_url(cik: str, accession: str, primary_document: str) -> str:
    """Build a direct link to a filing.

    Accession numbers look like 0001478242-25-000042. The folder name on
    EDGAR is the same number with the dashes removed.
    """
    base = ARCHIVES_URL.format(
        cik_int=int(cik),  # int() strips the leading zeros the path doesn't use
        accession_nodash=accession.replace("-", ""),
    )
    if primary_document:
        return f"{base}/{primary_document}"
    # No primary document listed: link to the filing's index page instead.
    return f"{base}/{accession}-index.htm"


def extract_filings(payload: dict, cik: str) -> list[dict]:
    """Turn the API's column-oriented data into a list of filing records.

    EDGAR returns filings as parallel arrays (one array of form types, one of
    dates, and so on) rather than a list of objects, so we zip them together.
    The arrays are ordered newest filing first.
    """
    recent = (payload.get("filings") or {}).get("recent") or {}
    accessions = recent.get("accessionNumber") or []
    forms = recent.get("form") or []
    dates = recent.get("filingDate") or []
    documents = recent.get("primaryDocument") or []
    descriptions = recent.get("primaryDocDescription") or []

    filings = []
    for i, accession in enumerate(accessions):
        filings.append({
            "accession": accession,
            "form": forms[i] if i < len(forms) else "",
            "filing_date": dates[i] if i < len(dates) else "",
            "description": descriptions[i] if i < len(descriptions) else "",
            "url": filing_url(cik, accession, documents[i] if i < len(documents) else ""),
        })
    return filings


# ---------------------------------------------------------------------------
# Deciding what is "new"
# ---------------------------------------------------------------------------

def select_new(filings: list[dict], last_seen: dict | None, first_run_limit: int) -> list[dict]:
    """Return the filings to report, newest first.

    - No saved state for this company (first run) -> the newest N filings.
    - We find the accession we saw last time -> everything above it is new.
    - We don't find it (it aged out of the recent window, or the state file
      was hand-edited) -> fall back to comparing filing dates.
    """
    if not filings:
        return []

    if not last_seen or not last_seen.get("last_accession"):
        return filings[:first_run_limit]

    last_accession = last_seen["last_accession"]
    for index, filing in enumerate(filings):
        if filing["accession"] == last_accession:
            return filings[:index]

    last_date = last_seen.get("last_filing_date", "")
    if not last_date:
        return filings[:first_run_limit]
    # Dates are ISO strings (YYYY-MM-DD), so a plain string comparison works.
    return [f for f in filings if f["filing_date"] > last_date]


def filter_forms(filings: list[dict], wanted: set[str]) -> list[dict]:
    """Keep only the requested form types (case-insensitive). Empty set = keep all."""
    if not wanted:
        return filings
    return [f for f in filings if f["form"].upper() in wanted]


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

def format_digest(results: list[dict], first_run_companies: list[str]) -> str:
    """Build the plain-text digest that gets printed at the end of a run."""
    lines = []
    total = sum(len(r["filings"]) for r in results)

    lines.append("=" * 72)
    lines.append("SEC EDGAR FILINGS DIGEST")
    lines.append("=" * 72)

    if first_run_companies:
        lines.append("")
        lines.append("First run for: " + ", ".join(first_run_companies))
        lines.append("Showing the most recent filings as a starting point.")

    for result in results:
        company = result["company"]
        label = company["name"]
        if company.get("ticker"):
            label = f"{label} ({company['ticker']})"

        lines.append("")
        lines.append("-" * 72)
        if result.get("error"):
            lines.append(f"{label}: ERROR - {result['error']}")
            continue
        if not result["filings"]:
            lines.append(f"{label}: no new filings")
            continue

        lines.append(f"{label}: {len(result['filings'])} new filing"
                     f"{'s' if len(result['filings']) != 1 else ''}")
        for filing in result["filings"]:
            lines.append("")
            lines.append(f"  Form:  {filing['form']}")
            lines.append(f"  Filed: {filing['filing_date']}")
            if filing.get("description"):
                lines.append(f"  Doc:   {filing['description']}")
            lines.append(f"  URL:   {filing['url']}")

    lines.append("")
    lines.append("=" * 72)
    lines.append(f"Total: {total} filing{'s' if total != 1 else ''} across "
                 f"{len(results)} companies")
    lines.append("=" * 72)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Check SEC EDGAR for new filings from a list of companies.")
    parser.add_argument("--companies", type=Path, default=DEFAULT_COMPANIES_FILE,
                        help="path to the company list (default: companies.json)")
    parser.add_argument("--state", type=Path, default=DEFAULT_STATE_FILE,
                        help="path to the state file (default: state.json)")
    parser.add_argument("--first-run-limit", type=int, default=5, metavar="N",
                        help="filings to show per company when there is no state (default: 5)")
    parser.add_argument("--all", action="store_true",
                        help="ignore saved state and show the most recent filings")
    parser.add_argument("--dry-run", action="store_true",
                        help="print the digest but do not update the state file")
    parser.add_argument("--forms", default="", metavar="LIST",
                        help="only report these form types, e.g. --forms 8-K,10-Q")
    parser.add_argument("--email", action="store_true",
                        help="also email the digest (configured via environment variables)")
    parser.add_argument("--email-always", action="store_true",
                        help="with --email, send even when there are no new filings")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    user_agent = os.environ.get("SEC_USER_AGENT", DEFAULT_USER_AGENT)
    if "example.com" in user_agent:
        print("Warning: set SEC_USER_AGENT (or edit DEFAULT_USER_AGENT) to your own\n"
              "         name and email. The SEC may throttle anonymous requests.\n",
              file=sys.stderr)

    companies = load_companies(args.companies)
    state = {} if args.all else load_state(args.state)
    wanted_forms = {f.strip().upper() for f in args.forms.split(",") if f.strip()}

    results = []
    first_run_companies = []
    new_state = dict(state)
    had_error = False

    for index, company in enumerate(companies):
        if index:
            time.sleep(REQUEST_DELAY_SECONDS)  # stay under the SEC's rate limit

        cik = company["cik"]
        last_seen = state.get(cik)
        if not last_seen:
            first_run_companies.append(company["name"])

        try:
            payload = fetch_submissions(cik, user_agent)
        except urllib.error.HTTPError as exc:
            message = f"HTTP {exc.code} from EDGAR"
            if exc.code == 403:
                # Two causes, neither obvious from the status code alone.
                message += (" - either SEC_USER_AGENT has no contact email"
                            " (set it to something like 'Jane Doe"
                            " jane@example.org'), or EDGAR has blocked this"
                            " IP. Cloud and datacenter addresses are often"
                            " refused even with a valid User-Agent.")
            elif exc.code == 404:
                message += f" - is CIK {cik} correct?"
            elif exc.code == 429:
                message += " - rate limited; wait a minute and try again."
            results.append({"company": company, "filings": [], "error": message})
            had_error = True
            continue
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError, OSError) as exc:
            results.append({"company": company, "filings": [], "error": str(exc)})
            had_error = True
            continue

        filings = extract_filings(payload, cik)
        new_filings = filter_forms(select_new(filings, last_seen, args.first_run_limit),
                                   wanted_forms)
        results.append({"company": company, "filings": new_filings, "error": None})

        # Record the newest filing we saw, whether or not it matched --forms.
        # Otherwise a filtered run would make unmatched filings look "new" later.
        if filings:
            new_state[cik] = {
                "company": company["name"],
                "last_accession": filings[0]["accession"],
                "last_filing_date": filings[0]["filing_date"],
            }

    digest = format_digest(results, first_run_companies)
    print(digest)

    if args.email and not send_email_digest(results, digest, args.email_always):
        had_error = True

    if args.dry_run:
        print("\n(dry run: state file not updated)")
    else:
        save_state(args.state, new_state)

    return 1 if had_error else 0


def send_email_digest(results: list[dict], digest: str, always: bool) -> bool:
    """Email the digest. Returns False if something went wrong.

    A failure here is reported but never discards the digest: it has already
    been printed, and on a non-dry run the state file still advances. Losing
    the run because the mail server was down would be worse than a missed
    email.
    """
    new_count = sum(len(r["filings"]) for r in results)
    companies = [r["company"]["name"] for r in results if r["filings"]]

    if not new_count and not always:
        print("\n(nothing new, so no email sent; use --email-always to send anyway)")
        return True

    try:
        config = emailer.load_email_config()
    except emailer.EmailConfigError as exc:
        print(f"\nEmail not sent: {exc}", file=sys.stderr)
        return False

    subject = emailer.build_subject(new_count, companies)
    try:
        emailer.send_digest(config, subject, digest)
    except (OSError, smtplib.SMTPException) as exc:
        print(f"\nEmail not sent: {type(exc).__name__}: {exc}", file=sys.stderr)
        return False

    print(f"\nEmailed to {', '.join(config.recipients)}")
    return True


if __name__ == "__main__":
    sys.exit(main())
